### ISSUE TITLE
Some cops don't work with test/factories

### ISSUE THREAD

**Issue by gravitystorm** [rubocop/rubocop-factory_bot#53]
I found out today that some of the cops don't work if you are using factory_bot with minitest, and have your factory definitions in `test/factories/` instead of `spec/factories/`.

After extraction from rubocop-rspec, the [default configuration](https://github.com/rubocop/rubocop-factory_bot/blob/afc310efc27661d673349aa560b3559dae1ab7b5/config/default.yml) has been adapted to support code under `test` (in addition to `spec`)

```yaml
FactoryBot:
  Enabled: true
  Include:
    - "**/*_spec.rb"
    - "**/spec/**/*"
    - "**/test/**/*"
    - "**/features/support/factories/**/*.rb"
 ```

but some cops, for example `FactoryBot/AttributeDefinedStatically` narrow this set of includes, and so don't spot e.g. `test/factories.rb` or `test/factories/**/*.rb`

```yaml
FactoryBot/AttributeDefinedStatically:
  Description: Always declare attribute values as blocks.
  Enabled: true
  Include:
    - spec/factories.rb
    - spec/factories/**/*.rb
    - features/support/factories/**/*.rb
 ```

I think all of these cops should have these two paths added to their `Include` configuration.
